export type Sport = 'Футбол' | 'Плавание' | 'Гимнастика' | 'Баскетбол' | 'Танцы' | 'Единоборства' | 'Конный спорт' | 'Лёгкая атлетика' | 'Пулевая стрельба' | 'Фехтование' | 'Современное пятиборье' | 'Настольный теннис' | 'Тяжёлая атлетика'

export type Group = {
  id: number
  sport: Sport
  title: string
  school: string
  district: string
  address: string
  ageMin: number
  ageMax: number
  schedule: string
  price: string
  coach: string
  coachExperience: string
  description: string
  requirements: string
  newGroup: boolean
  places: number
  image: string
}

export const sports: { name: Sport; emoji: string; description: string; about: string; benefits: string; color: string; photo: string; photoCredit?: string; photoSource?: string }[] = [
  { name: 'Футбол', emoji: '⚽', description: 'Команда и характер', about: 'Подвижная командная игра, в которой ребёнок учится взаимодействовать с другими и принимать решения на ходу. Для первого занятия достаточно удобной спортивной формы.', benefits: 'Командная работа · координация · выносливость', color: 'peach', photo: 'https://images.pexels.com/photos/274422/pexels-photo-274422.jpeg?w=1100' },
  { name: 'Плавание', emoji: '🏊', description: 'Уверенность в воде', about: 'Занятия в воде помогают освоиться в бассейне и постепенно выучить технику плавания. Начинающим подойдут группы с обучением с нуля.', benefits: 'Координация · выносливость · уверенность в воде', color: 'blue', photo: 'https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?w=1100' },
  { name: 'Гимнастика', emoji: '🤸', description: 'Гибкость и сила', about: 'Гимнастика знакомит ребёнка с возможностями своего тела через упражнения на равновесие, растяжку и координацию. Подготовка для начинающих не требуется.', benefits: 'Гибкость · баланс · координация', color: 'lavender', photo: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?w=1100' },
  { name: 'Баскетбол', emoji: '🏀', description: 'Движение и игра', about: 'Игра с мячом, в которой важны движение, взаимодействие и внимание. На первых тренировках дети осваивают ведение, передачи и броски.', benefits: 'Командная работа · ловкость · реакция', color: 'yellow', photo: 'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?w=1100' },
  { name: 'Танцы', emoji: '💃', description: 'Ритм и творчество', about: 'Танцевальные занятия позволяют выражать себя в движении, разучивать связки и выступать вместе с группой. Начать можно без специальной подготовки.', benefits: 'Чувство ритма · координация · самовыражение', color: 'pink', photo: 'https://images.pexels.com/photos/1701194/pexels-photo-1701194.jpeg?w=1100' },
  { name: 'Единоборства', emoji: '🥋', description: 'Дисциплина и смелость', about: 'На тренировках дети изучают базовые движения, правила безопасности и уважительное отношение к партнёру. Начинают постепенно, в подходящей по возрасту группе.', benefits: 'Самоконтроль · координация · дисциплина', color: 'mint', photo: 'https://images.pexels.com/photos/260352/pexels-photo-260352.jpeg?w=1100' },
  { name: 'Конный спорт', emoji: '🐎', description: 'Доверие и баланс', about: 'Общение с лошадью и основы верховой езды развивают равновесие, внимание и ответственность. Условия допуска и возраст нужно уточнять непосредственно в школе.', benefits: 'Баланс · внимание · ответственность', color: 'peach', photo: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg?w=1100' },
  { name: 'Лёгкая атлетика', emoji: '🏃', description: 'Бег, прыжки и движение', about: 'Лёгкая атлетика объединяет беговые и технические дисциплины. На первых занятиях дети знакомятся с движением и постепенно развивают выносливость.', benefits: 'Скорость · координация · выносливость', color: 'mint', photo: 'https://images.pexels.com/photos/2526878/pexels-photo-2526878.jpeg?w=1100' },
  { name: 'Пулевая стрельба', emoji: '🎯', description: 'Точность и концентрация', about: 'Спортивная стрельба учит сосредоточенности и соблюдению правил безопасности. Возраст и условия допуска определяет школа.', benefits: 'Концентрация · выдержка · точность', color: 'yellow', photo: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Running_target_shooting.jpg', photoCredit: 'Фото: pxfuel · CC0', photoSource: 'https://commons.wikimedia.org/wiki/File:Running_target_shooting.jpg' },
  { name: 'Фехтование', emoji: '🤺', description: 'Тактика и реакция', about: 'Фехтование — динамичный поединок с чёткими правилами, где важны реакция, дистанция и уважение к сопернику.', benefits: 'Реакция · координация · тактика', color: 'lavender', photo: 'https://upload.wikimedia.org/wikipedia/commons/2/22/French_regional_fencing_competition.JPG' },
  { name: 'Современное пятиборье', emoji: '🏅', description: 'Несколько дисциплин в одной', about: 'Многоборье объединяет разные спортивные навыки. Состав дисциплин, возраст и порядок подготовки стоит уточнить у тренера школы.', benefits: 'Разностороннее развитие · выносливость · концентрация', color: 'blue', photo: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Modern_Pentathlon_Rio_2016_Olympics.jpg', photoCredit: 'Фото: Rio 2016 photographers · CC BY-SA 4.0', photoSource: 'https://commons.wikimedia.org/wiki/File:Modern_Pentathlon_Rio_2016_Olympics.jpg' },
  { name: 'Настольный теннис', emoji: '🏓', description: 'Скорость и внимание', about: 'Быстрая игра с ракеткой тренирует реакцию, точность движений и умение принимать решения за доли секунды.', benefits: 'Реакция · внимание · координация', color: 'pink', photo: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Khayala_playing_table_tennis.jpg', photoCredit: 'Фото: karpidis · CC BY 2.0', photoSource: 'https://commons.wikimedia.org/wiki/File:Khayala_playing_table_tennis.jpg' },
  { name: 'Тяжёлая атлетика', emoji: '🏋️', description: 'Сила и техника', about: 'Занятия строятся вокруг техники движений и постепенной подготовки. Возрастные ограничения и допуск обязательно уточняйте в школе.', benefits: 'Техника · сила · самодисциплина', color: 'peach', photo: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?w=1100' },
]

// Макеты карточек. Заменить на подтверждённый реестр школ и их актуальные объявления.
export const groups: Group[] = [
  { id: 1, sport: 'Футбол', title: 'Футбол: первая команда', school: 'Пример школы · Футбол', district: 'Луганск', address: 'Адрес уточняется', ageMin: 6, ageMax: 9, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Молодой тренер (пример)', coachExperience: 'Новая группа · пример размещения', description: 'Первое знакомство с футболом через игру, упражнения с мячом и работу в команде.', requirements: 'Для начинающих; удобная форма и спортивная обувь. Точные условия уточняются в школе.', newGroup: true, places: 6, image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=900&q=85' },
  { id: 2, sport: 'Плавание', title: 'Плавание с нуля', school: 'Пример школы · Плавание', district: 'Луганск', address: 'Адрес уточняется', ageMin: 5, ageMax: 8, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Молодой тренер (пример)', coachExperience: 'Новая группа · пример размещения', description: 'Первые занятия в воде: освоение бассейна, дыхание и базовые движения.', requirements: 'Для начинающих; требования к допуску в бассейн уточняются в школе.', newGroup: true, places: 4, image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=900&q=85' },
  { id: 3, sport: 'Гимнастика', title: 'Гимнастика для начинающих', school: 'Пример школы · Гимнастика', district: 'Луганск', address: 'Адрес уточняется', ageMin: 4, ageMax: 7, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Тренер уточняется', coachExperience: 'Информация ожидается от школы', description: 'Занятия на координацию, гибкость и равновесие с учётом возраста ребёнка.', requirements: 'Подготовка не требуется; форма и порядок записи уточняются в школе.', newGroup: false, places: 3, image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=900&q=85' },
  { id: 4, sport: 'Баскетбол', title: 'Баскетбол: играем вместе', school: 'Пример школы · Баскетбол', district: 'Луганск', address: 'Адрес уточняется', ageMin: 8, ageMax: 12, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Молодой тренер (пример)', coachExperience: 'Новая группа · пример размещения', description: 'Ведение мяча, броски и командная игра для тех, кто хочет попробовать баскетбол.', requirements: 'Для начинающих; удобная спортивная форма. Условия набора уточняются.', newGroup: true, places: 8, image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=900&q=85' },
  { id: 5, sport: 'Танцы', title: 'Современные танцы', school: 'Пример школы · Танцы', district: 'Луганск', address: 'Адрес уточняется', ageMin: 6, ageMax: 10, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Тренер уточняется', coachExperience: 'Информация ожидается от школы', description: 'Движение под музыку, развитие чувства ритма и знакомство с хореографией.', requirements: 'Для начинающих; удобная одежда. Дополнительные условия уточняются.', newGroup: false, places: 5, image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=900&q=85' },
  { id: 6, sport: 'Единоборства', title: 'Дзюдо: первые шаги', school: 'Пример школы · Единоборства', district: 'Луганск', address: 'Адрес уточняется', ageMin: 7, ageMax: 11, schedule: 'Расписание уточняется', price: 'Условия уточняются', coach: 'Тренер уточняется', coachExperience: 'Информация ожидается от школы', description: 'Базовые движения, безопасное взаимодействие с партнёром и дисциплина.', requirements: 'Для начинающих; требования к форме и допуску уточняются в школе.', newGroup: false, places: 7, image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=900&q=85' },
]

export const districts = ['Все районы', ...Array.from(new Set(groups.map((group) => group.district))).sort()]
